/*
 * Initial version generated by https://www.embedgooglemap.net
 */

import React from 'react'
import styles from './Map.module.css'

export default function Map () {
  return (
    <div className={styles.mapOuter}>
      <div className={styles.gmapCanvas}>
        <iframe
          title="Google Map of Mar Adentro location"
          width="445"
          height="276"
          id="gmap_canvas"
          src="https://maps.google.com/maps?q=Mar%20Adentro%20Diving%2C%20Mahahual%2C%20Mexico&t=&z=15&ie=UTF8&iwloc=&output=embed"
          frameBorder="0"
          scrolling="no"
          marginHeight="0"
          marginWidth="0">
        </iframe>
      </div>
    </div>
  )
}
